### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by xlvector** [haria/mxnet-multi-task-example#1]
@property
    def provide_label(self):
        provide_label = self.data_iter.provide_label[0]
        # Different labels should be used here for actual application
        return [('softmax1_label', provide_label[1]), \
                ('softmax2_label', provide_label[1])]

Here, both softmax1_label, and softmax2_label equals provide_label[1]?

**Comment by hariag** [comment]
provide_label[1] output the shape info, both softmax1_label and softmax2_label have same shape. so it doesn't matter.
 provide_label[0] output something like "softmax_label".

**Comment by xlvector** [comment]
thanks，got it
