### ISSUE TITLE
What is module get_data,how can I get it?

### ISSUE THREAD

**Issue by guosusu** [haria/mxnet-multi-task-example#3]
I follow your example, however, an error occurs.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-986d07029914> in <module>()
      6 # code to automatically download dataset
      7 sys.path.append( "../../tests/python/common")
**----> 8 import get_data**
      9 import mxnet as mx
     10 

**ModuleNotFoundError: No module named 'get_data'**

So,What is module get_data,how can I get it? @hariag 
Thanks

**Comment by hariag** [comment]
Hi,
this example is out of date, it was commit to here two years ago.
if you still want to reproducem you can find the get_data module from here https://github.com/apache/incubator-mxnet/blob/20160531/tests/python/common/get_data.py

thank you.
